# Example launchr configuration (TOML)

# Bookmarks
[[bookmarks]]
name = "Home"
path = "~"
bookmark_type = "directory"

[[bookmarks]]
name = "Project Docs"
path = "https://example.com/docs"
bookmark_type = "url"

# SSH Hosts
[[ssh_hosts]]
name = "prod"
host = "prod.example.com"
port = 22
user = "deploy"

[[ssh_hosts]]
name = "staging"
host = "staging.example.com"
port = 22
user = "deploy"

# Scripts
[[scripts]]
name = "backup"
command = "bash ~/scripts/backup.sh"
description = "Run backup script"

[[scripts]]
name = "clean-temp"
command = "rm -rf /tmp/*"
description = "Clean temp files"

# Git repo search paths
git_search_paths = ["~/projects", "~/work"]

# Scratchpad
[scratchpad]
editor = "nvim"              # optional
# directory = "~/notes"      # optional

# Config files (Configs module)
[[configs]]
name = "Shell Profile"
path = "~/.bashrc"
category = "Shell"
description = "Bash profile"
# editor = "nvim"            # optional per-entry

[[configs]]
name = "Git Config"
path = "~/.gitconfig"
category = "Git"
description = "Global git configuration"

[[configs]]
name = "Editor Settings"
path = "~/.config/nvim"
category = "Editor"
description = "Neovim configuration"

# Optional settings (placeholders; not read by the app yet)
# [docker]
# show_all = false

# [services]
# user_scope = "system"  # or "user"

# [network]
# default_filter = "ESTABLISHED"

# [apps]
# path_exclude = ["/snap/bin", "/opt/ignore"]

# [shell]
# default_dir = "~"
# history_size = 1000

# [scratchpad]
# filename_pattern = "note_%Y%m%d_%H%M%S.txt"
# extension = ".txt"


